### ISSUE TITLE
이슈로 일일 과제를 주는건 어떤가요?

### ISSUE THREAD

**Issue by MuhunKim** [ChalkPE/DailyQuest#1]
[여기에](https://github.com/ChalkPE/DailyQuest/labels) DailyQuest 레이블 만들어놓고..

대충 README 에서
> "DailyQuest 레이블 박아주시고 이슈로 일일 도전과제 주세요~"

라고 하면 좋을것 같네요.

**Comment by MuhunKim** [comment]
+ ps 흥미있는 퀘스트는 ~~한줄 코딩이 불가능한~~  Python으로 풀어서 PR 보낼게요~

**Comment by ChalkPE** [comment]
좋은 아이디어 감사합니다!

**Comment by MuhunKim** [comment]
아 맞다.. 레이블은 저장소 권한이 없으면 안되요 ㅋㅋㅋ
